name: Django CI/CD

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to DigitalOcean
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PROJECT_PATH: /var/www/pixify
      run: |
        ssh -i "${{ secrets.PRIVATE_KEY }}" -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
        cd $PROJECT_PATH
        git pull
        source venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        sudo systemctl restart nginx
        EOF
